### ISSUE TITLE
Using Maven Always Green even on failed test

### ISSUE THREAD

**Issue by ccit-spence** [robertraaijmakers/vsts-extension-huebuildlamp#2]
Trying this out and so far it is always green even if my Maven build fails a unit test.

**Comment by robertraaijmakers** [comment]
Hi, can you give a bit more details about your set-up and is ment by 'always green'?

**Comment by ccit-spence** [comment]
It is a Spring Boot project with Unit tests.  Maven shows that the build fails due to failing Unit test.  In the logs I see that the email sent is stating Green.  

If all Unit tests pass.  The email sent is also showing Green.

**Comment by robertraaijmakers** [comment]
I just checked and am not able to reproduce the issue. Can you add you log file so that I can see if some settings are different then mine? And maybe some screenshots of the step configuration?

Did you check the "Allow scripts to access OAuth token. Enables scripts and other processes launched during the build to access the OAuth token via the System.AccessToken variable" under "Options" in the build configuration?

**Comment by robertraaijmakers** [comment]
@ccit-spence did you get it to work already? If there is no response I will close this issue since I can't reproduce it.

**Comment by ccit-spence** [comment]
@robertraaijmakers Sorry, I have not had any time to test further.  I will go ahead and close the issue.  Fighting my own VSTS / Core 1.1 issues right now.
